
[core]


name: rifle infantry
displayDescription: -tiny health \n -medium damage assault rifle \n -cheap \n -very fast

class: CustomUnitMetadata
price: 400
maxHp: 25
mass: 1500

techLevel: 1
buildSpeed: 0.0020
#availableInDemo: true

radius: 5
displayRadius: 4

isBio: false
softCollisionOnAll: 0

builtFrom_1_name: landFactory
builtFrom_1_pos:  6

[graphics]
total_frames: 1

image:        rifle_infantry.png
image_wreak:  NONE
image_turret: NONE


imageScale:0.8
turretImageScale:0.8

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 4

isFixedFiring: true

maxAttackRange: 310
shootDelay: 10

[turret_1]
#
x: -2
y: 1

projectile: 1

turnSpeedAcceleration: 1.0

shoot_sound:tank_firing
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC

canShoot: true


recoilOffset: -2


[projectile_1]
directDamage: 8
life: 60
speed: 18

frame: 1

drawSize: 1


[movement]
movementType: LAND
moveSpeed: 1.7
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 4.1
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false





