
[core]
name: Cannon Mech
displayDescription: -slow \n -has medium cannon \n -can only attack ground \n -my first unit

copyFrom: mech_med_common.ini

price: 1200
maxHp: 800
mass: 4500

techLevel: 1
buildSpeed: 0.0012
#availableInDemo: true

radius: 20
displayRadius: 20



#energyMax: 4
#energyRegen: 0.02
#energyNeedsToRechargeToFull: true



[graphics]

image: topCannon.png


image_wreak:  NONE
#image_turret: topCannon.png


image_shadow: SHADOW:topCannon.png





[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 3


maxAttackRange: 160
shootDelay: 60

turretRotateWithBody: false

[turret_mainBody]
x: 0
y: 0
idleDir:0

barrelX: 0
barrelY: 25



turnSpeed: 2.9
turnSpeedAcceleration: 0.3

#canShoot: false


#note: lock_body_rotation_with_main_turret is needed for recoil to work on the body
recoilOffset: -1
recoilOutTime: 2
recoilReturnTime: 14


projectile: 1


shoot_sound:plasma_fire
shoot_sound_vol:0.03
#shoot_flame:small
#shoot_light:#FFccCCEE
shoot_flame:CUSTOM:lightSlowFade

canShoot: true


#energyUsage: 1
warmup:7
#chargeEffectImage: SHARED:lighting_charge.png
chargeEffectImage: SHARED:lighting_charge.png




idleSweepAngle:20
idleSweepSpeed:0.30
idleSweepDelay:100
idleSweepAddRandomDelay:50
idleSweepCondition: if not self.isMoving()


[effect_lightSlowFade]
image: SHARED:light_50.png
life: 20
fadeOut: true
attachedToUnit: true
#color: #63e6e8
color: #FFEECCCC
scaleFrom: 0.2
scaleTo: 0.5
alpha: 0.5
drawUnderUnits:true


[projectile_1]
directDamage: 75
life: 90

frame: 11

drawSize: 0.7




#speed: 2
speed: 0
targetSpeed: 8
targetSpeedAcceleration: 1.5

effectOnCreate: CUSTOM:projectileLight




[effect_projectileLight]
priority:high

image: SHARED:light_50.png
life: 100
fadeOut: true
attachedToUnit: true
color: #FFEECCCC
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.6
drawUnderUnits:false
liveAfterAttachedDies: false




