
[core]
name: turret v2
displayDescription: better than normal turret \n attacks both land and air \n more armor \n less upgrades

price: 2100
maxHp: 1400
mass: 3000

techLevel: 1
buildSpeed: 0.001

footprint: -1,-1,0,0

constructionFootprint: -1,-1,0,0

radius: 16
buildingSelectionOffset: -8

builtFrom_1_name: builder
builtFrom_1_pos:  6

builtFrom_2_name: combat_engineer
builtFrom_2_pos:  6

builtFrom_3_name: mech_engineer
builtFrom_3_pos:  6

builtFrom_4_name: experimental_spider
builtFrom_4_pos:  6

isBuilding: true

[graphics]
total_frames: 1

image:        turret_base.png
image_wreak:  turret_base_dead.png
image_turret: turret_gun_v2.png

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1

image_offsetX: -10
image_offsetY: -10

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 22
turretTurnSpeed: 6


maxAttackRange: 260
shootDelay: 25



[turret_1]

x: -10
y: 16


shoot_sound:firing3
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC




#idleSpin: 0.8

idleSweepAngle:20
idleSweepDelay:210
idleSweepSpeed:0.2


recoilOffset: -0.5
recoilOutTime: 6
recoilReturnTime: 12


[projectile_1]
directDamage: 80
life: 240
speed: 6
#ballistic: true
#ballistic_delaymove_height:0
#ballistic_height: 4
frame: 1
#areaDamage: 65
#areaRadius: 45

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]

buildPriority: 0.22
noneInBaseExtraPriority: 0.17

maxEachBase: 3





