
[core]
name: sharded turret
displayDescription: -basic sharded ground turret \n -good for long defence \n -upgradeable

price: 650
maxHp: 630
mass: 3000

techLevel: 1
buildSpeed: 0.003

footprint: -1,-1,0,0

constructionFootprint: -1,-1,0,0

isBuilding: true

radius: 16
buildingSelectionOffset: -8

builtFrom_1_name: alpha
builtFrom_1_pos:  6

[action_upgradeMK2]
convertTo: sharded turret MK2
price:  1200
text: sharded turret MK2
description: -more range \n -more HP \n -faster and more damage
displayType: Upgrade
buildSpeed: 0.002
pos: 0.2
iconExtraImage: SHARED:icon_upgrade_top.png
iconExtraColor: #AAFFFFFF

[graphics]
total_frames: 1

image:        sharded_base.png
image_wreak:  turret_base_dead.png
image_turret: sharded_turret.png

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1

image_offsetX: -10
image_offsetY: -10

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 22
turretTurnSpeed: 6


maxAttackRange: 200
shootDelay: 25



[turret_1]

x: -10
y: 10


shoot_sound:firing3
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC




#idleSpin: 0.8

idleSweepAngle:20
idleSweepDelay:210
idleSweepSpeed:0.2


recoilOffset: -0.5
recoilOutTime: 6
recoilReturnTime: 12


[projectile_1]
directDamage: 42
life: 240
speed: 6
#ballistic: true
#ballistic_delaymove_height:0
#ballistic_height: 4
frame: 1
#areaDamage: 65
#areaRadius: 45

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]

buildPriority: 0.22
noneInBaseExtraPriority: 0.17

maxEachBase: 3





