
[core]
name: pool Drill
displayDescription: -mines resources out of resource pools \n -later levels can mine thorium a little bit
copyFrom: extractor_common.ini
price: 650
maxHp: 800
techLevel: 1
buildSpeed: 0.0010

#price per credit: $87
generation_resources: credits=9

[action_upgradeT2]
convertTo: extractorT2
#price:  1200 #1.13
price:  1400
#price per credit: $233 (out of date)
description: placeholder upgrade
displayType: upgrade
buildSpeed: 0.0006
iconExtraImage: SHARED:icon_upgrade_top.png
iconExtraColor: #AAFFFFFF

[graphics]
image:        poolDrill.png




