
[core]


name: autocannon tank
displayDescription: -second sharded tank \n -armed with ground only autocannon \n -small damage \n -fast


class: CustomUnitMetadata
armour: 5
price: 860
maxHp: 220
mass: 3000

techLevel: 1
buildSpeed: 0.0012
#availableInDemo: true

radius: 14
displayRadius: 14

isBio: false
softCollisionOnAll: 0

builtFrom_1_name: tankyard
builtFrom_1_pos:  3

[graphics]
total_frames: 1

image:        autocannon_tank.png
image_wreak:  NONE
image_turret: autocannon_gun.png


imageScale:0.8
turretImageScale:0.8

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

dustEffect: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 20
turretTurnSpeed: 4


maxAttackRange: 175
shootDelay: 30

[turret_1]
#
x: 0
y: 0

projectile: 1

turnSpeedAcceleration: 1.0

shoot_sound:tank_firing
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC

canShoot: true


recoilOffset: -2


[projectile_1]
directDamage: 24
life: 60
speed: 5

frame: 1

drawSize: 1


[movement]
movementType: LAND
moveSpeed: 1.1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 4.1
turnAcceleration: 0.25

moveSlidingMode :false
moveIgnoringBody:false
